<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.3 setup script
 * Date: Wed, 26 Jul 2017 14:17:11 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
// $cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '5555';

/* End of servers configuration */

$cfg['blowfish_secret'] = '+-{Z#~j@Q>%SBY]2pS^-NkZ-"Jv0lG}f';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>